version: '3.8'
services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    restart: always

volumes:
  db_data:
    driver: local